config/routes.rb
Rails.application.routes.draw do
  resources :athletes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:name, :lastName, :birthDate, :sex, :idCountry, :idClub, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_with(model: athlete, local: true) do |form| %>
  <% if athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% athlete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :athlete_name %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, id: :athlete_lastName %>
  </div>

  <div class="field">
    <%= form.label :birthDate %>
    <%= form.date_select :birthDate, id: :athlete_birthDate %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, id: :athlete_sex %>
  </div>

  <div class="field">
    <%= form.label :idCountry %>
    <%= form.number_field :idCountry, id: :athlete_idCountry %>
  </div>

  <div class="field">
    <%= form.label :idClub %>
    <%= form.number_field :idClub, id: :athlete_idClub %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :athlete_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<h1>Editing Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

app/views/athletes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Athletes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Birthdate</th>
      <th>Sex</th>
      <th>Idcountry</th>
      <th>Idclub</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @athletes.each do |athlete| %>
      <tr>
        <td><%= athlete.name %></td>
        <td><%= athlete.lastName %></td>
        <td><%= athlete.birthDate %></td>
        <td><%= athlete.sex %></td>
        <td><%= athlete.idCountry %></td>
        <td><%= athlete.idClub %></td>
        <td><%= athlete.email %></td>
        <td><%= link_to 'Show', athlete %></td>
        <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
        <td><%= link_to 'Destroy', athlete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Athlete', new_athlete_path %>

app/views/athletes/new.html.erb
<h1>New Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Back', athletes_path %>

app/views/athletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @athlete.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @athlete.lastName %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @athlete.birthDate %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @athlete.sex %>
</p>

<p>
  <strong>Idcountry:</strong>
  <%= @athlete.idCountry %>
</p>

<p>
  <strong>Idclub:</strong>
  <%= @athlete.idClub %>
</p>

<p>
  <strong>Email:</strong>
  <%= @athlete.email %>
</p>

<%= link_to 'Edit', edit_athlete_path(@athlete) %> |
<%= link_to 'Back', athletes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fedachi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>